// This file defines the "shape/form" of the data
// Typescript uses these types to alert if there's a type error
// Example : if I write project.titlee (typo),
// TypeScript will signal it immediately

// ─── User Profile ───────────────────────────────────────────
export type Profile = {
  id: string           // UUID generated by Supabase Auth
  name: string
  first_name: string | null
  last_name: string | null
  country: string | null   // null = user hasn't filled this field yet
  bio: string | null
  school: string | null
  major: string | null
  builder_type: 'student' | 'bootcamp' | 'self_learner' | 'professional' | null
  institution: string | null
  program: string | null
  avg_rating: number   // Average calculated automatically by the SQL trigger
  ratings_count: number // Total number of ratings received
  preferred_contact_type: string | null
  preferred_contact_value: string | null
  created_at: string   // Date in ISO 8601 format e.g., "2024-01-15T10:30:00Z"
}

// ─── Project ───────────────────────────────────────────────────────
export type Project = {
  id: string
  owner_id: string     // Reference to profiles.id — the user who created this project
  title: string
  problem: string | null
  //list exact values for this field
  level: 'Beginner' | 'Intermediate' | 'Advanced' | string
  domain: string | null
  status: 'open' | 'in_progress' | 'completed'
  duration: string | null // Ex: "2 weeks", "3 months"
  spots: number | null // number of collaborators wanted
  website_url: string | null
  github_url: string | null
  created_at: string
  is_public?: boolean

  // Privacy settings — true = visible to all, false = members + followers only
  show_build_log: boolean
  show_chat: boolean
  show_milestones: boolean
  show_team: boolean

  // this fields are optional because they only exist when we fetch a project with its related data using SQL joins
  // Example: when we fetch a project with its skills AND its author at the same time using SQL joins
  profiles?: Profile          // Project owner profile
  project_skills?: ProjectSkill[] // Skills wanted for this project

  //activity signals (ex: "update in Project X")
  project_members?: {user_id: string}[] // lists of members connected to this project
  project_updates?: { created_at: string }[] // last time this project was active (ex: "2 days ago")

}

// ─── Skills wanted for a project ─────────────────────────
export type ProjectSkill = {
  id: string
  project_id: string   // Reference to projects.id
  skill_needed: string // Ex: "Designer", "Data Scientist", "Dev Backend"
}

// ─── Connection Request ─────────────────────────────────────────
export type Connection = {
  id: string
  sender_id: string    // Reference to profiles.id — the user who sent the connection request
  message: string | null
  project_id: string   // Reference to projects.id — the project targeted by this connection request
  // Les 3 states possibles for a connection request :
  status: 'pending' | 'accepted' | 'rejected'
  created_at: string
}

// ─── Milestones ─────────────────────────────────────────
export type Milestone = {
  id: string
  project_id: string
  title: string
  completed: boolean
  position: number
  created_at: string
}

// ─── Update posted by a member in the project workspace ────────────────────────────────────────
export type ProjectUpdate = {
  id: string
  project_id: string
  author_id: string
  type: 'update' | 'milestone' | 'blocker' | 'decision' | 'demo'
  content: string
  created_at: string
  // Joint with the author's profile when fetching updates with SQL joins, to display the author's name and profile picture
  profiles?: {
    id: string
    name: string | null
    first_name: string | null
    last_name: string | null
    avg_rating: number
  }
}

// ─── Message in the group chat of a project ────────────────────────────────────────
export type ProjectMessage = {
  id: string
  project_id: string
  author_id: string
  content: string
  created_at: string
  profiles?: {
    id: string
    name: string | null
    first_name: string | null
    last_name: string | null
  }
}

// ─── Notification in-app ────────────────────────────────────────
export type Notification = {
  id: string
  user_id: string
  type: 'connection_request' | 'connection_accepted' | 'new_member' | 'new_message' | 'new_project_published'
  title: string
  body: string | null
  link: string | null
  read: boolean
  created_at: string
}

// ─── Follower of a project ────────────────────────────────────────
export type ProjectFollower = {
  id: string
  project_id: string
  user_id: string
  created_at: string
}

// ─── Comments/feedback of a builder on a project ─────────────────────────────────────────
export type ProjectComment = {
  id: string
  project_id: string
  author_id: string
  content: string
  created_at: string
  profiles?: {
    id: string
    name: string | null
    first_name: string | null
    last_name: string | null
    avg_rating: number
  }
}
